// This file is auto-generated by gen_header.py
#ifndef AoC_modules_H
#define AoC_modules_H

#include <map>
#include <string>
#include <vector>
#include "AoC.h"

AoC *day1_create();
AoC *day2_create();
AoC *day3_create();
AoC *day4_create();
AoC *day5_create();
AoC *day6_create();
AoC *day7_create();
AoC *day8_create();
AoC *day9_create();
AoC *day10_create();
AoC *day11_create();
AoC *day12_create();
AoC *day13_create();
AoC *day14_create();
AoC *day15_create();
AoC *day16_create();

using ModuleFuncPtr = AoC* (*)();

namespace AoCModules {
	std::map<std::string,ModuleFuncPtr> modules = {
		{"day1", day1_create},
		{"day2", day2_create},
		{"day3", day3_create},
		{"day4", day4_create},
		{"day5", day5_create},
		{"day6", day6_create},
		{"day7", day7_create},
		{"day8", day8_create},
		{"day9", day9_create},
		{"day10", day10_create},
		{"day11", day11_create},
		{"day12", day12_create},
		{"day13", day13_create},
		{"day14", day14_create},
		{"day15", day15_create},
		{"day16", day16_create}
	};
    std::vector<std::string> modules_order = {
		"day1",
		"day2",
		"day3",
		"day4",
		"day5",
		"day6",
		"day7",
		"day8",
		"day9",
		"day10",
		"day11",
		"day12",
		"day13",
		"day14",
		"day15",
		"day16"
    };
};

#endif
