// This file is auto-generated by gen_header.py
#ifndef AoC_modules_H
#define AoC_modules_H

#include <string>
#include <map>
#include "AoC.h"

AoC *day1_create(bool test);
AoC *day2_create(bool test);
AoC *day3_create(bool test);
AoC *day4_create(bool test);
AoC *day5_create(bool test);
AoC *day6_create(bool test);
AoC *day7_create(bool test);
AoC *day8_create(bool test);
AoC *day9_create(bool test);

using ModuleFuncPtr = AoC* (*)(bool);

namespace AoCModules {
	std::map<std::string,ModuleFuncPtr> modules = {
		{"day1", day1_create},
		{"day2", day2_create},
		{"day3", day3_create},
		{"day4", day4_create},
		{"day5", day5_create},
		{"day6", day6_create},
		{"day7", day7_create},
		{"day8", day8_create},
		{"day9", day9_create}
	};
};

#endif
